# .rubocop.yml
require:
  - rubocop-rails
  # Optional: - rubocop-rspec
# AllCops:


Style/Documentation:
  Enabled: false

Rails/NotNullColumn:
  Exclude:
    - 'db/migrate/**/*'

Rails/FilePath:
  Exclude:
    - 'config/initializers/*'
    
AllCops:
  SuggestExtensions: false
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    # Add other exclusions as needed

# Example: Configure a specific cop
Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

# You can also set the target Rails version explicitly if needed
# RuboCop Rails will attempt to infer it from Gemfile.lock otherwise
Rails:
  TargetRailsVersion: 5.2 # Or your specific Rails 5 version